file_format: "1"
id: hellojoy
name: hellojoy
type: shield
url: https://github.com/hellojoytown/hellojoy
requires: [nice_nano_v2]
features:
  - keys
  - bluetooth 
siblings:
  - hellojoy_left
  - hellojoy_right
